import { execFileSync } from "node:child_process"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"

// Builds the plugin bundles and stamps each one with its identity.
//
//   bun scripts/build.ts          # server + cli
//   bun scripts/build.ts server
//   bun scripts/build.ts cli
//
// The identity values are injected with `bun build --define` and read back in
// src/version.ts. They let a running plugin report which source it came from:
// package version, `git describe`, short sha, and whether the tree was dirty.
//
// `dist/build-info.json` records the same identity. `scripts/check-dist.ts`
// rebuilds with PLUGIN_BUILD_VERSION, PLUGIN_BUILD_DESCRIBE, PLUGIN_BUILD_SHA,
// and PLUGIN_BUILD_DIRTY pinned to the recorded values, so a committed dist/
// can be verified without depending on the checked-out git state.
//
// `git describe` is the human-facing field: it names the most recent release tag
// plus the commits since it (e.g. `v0.1.8-4-g64bff2f`), so a local build is
// always distinguishable from the published tarball it is based on.

const root = fileURLToPath(new URL("..", import.meta.url))

function git(args: string[]): string | null {
  try {
    const output = execFileSync("git", args, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim()
    return output.length > 0 ? output : null
  } catch {
    return null
  }
}

function isDirty(): boolean {
  try {
    // Only *source* changes make a build dirty. Two paths are generated or
    // rewritten and must be ignored:
    //   - package.json: `bun run ci:version` rewrites it to the release version
    //     moments before a publish build.
    //   - dist/: tracked build output, regenerated by this script.
    const output = execFileSync(
      "git",
      [
        "status",
        "--porcelain",
        "--untracked-files=no",
        "--",
        ".",
        ":(exclude)package.json",
        ":(exclude)dist",
      ],
      { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    )
    return output.trim().length > 0
  } catch {
    return false
  }
}

/**
 * Build identity overrides for reproducible checks. An empty value pins the
 * field to null; an unset variable lets the build detect the value from git.
 */
function stringOverride(name: string): string | null | undefined {
  const value = process.env[name]
  if (value === undefined) return undefined
  return value.length > 0 ? value : null
}

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8")) as {
  version?: unknown
}
const version = typeof pkg.version === "string" && pkg.version.length > 0 ? pkg.version : "0.0.0"
const dirtyOverride = stringOverride("PLUGIN_BUILD_DIRTY")
const buildInfo = {
  version: stringOverride("PLUGIN_BUILD_VERSION") ?? version,
  gitDescribe: stringOverride("PLUGIN_BUILD_DESCRIBE") ?? git(["describe", "--tags", "--always"]),
  gitSha: stringOverride("PLUGIN_BUILD_SHA") ?? git(["rev-parse", "--short", "HEAD"]),
  gitDirty: dirtyOverride === undefined ? isDirty() : dirtyOverride === "true",
}

// `bun build --define` takes space-separated KEY=VALUE pairs (the colon form is
// silently ignored on Bun 1.4.x). Values must be JSON literals.
const defineArgs = (
  [
    ["__PLUGIN_VERSION__", JSON.stringify(buildInfo.version)],
    ["__PLUGIN_GIT_DESCRIBE__", JSON.stringify(buildInfo.gitDescribe)],
    ["__PLUGIN_GIT_SHA__", JSON.stringify(buildInfo.gitSha)],
    ["__PLUGIN_GIT_DIRTY__", buildInfo.gitDirty ? "true" : "false"],
  ] as const
).flatMap(([key, value]) => ["--define", `${key}=${value}`])

type Target = "all" | "server" | "cli"

const serverExternals = ["@opencode-ai/plugin", "effect", "zod"]
const cliExternals = ["effect", "zod"]

function build(target: Exclude<Target, "all">) {
  const isServer = target === "server"
  const externals = isServer ? serverExternals : cliExternals
  const args = [
    "build",
    isServer ? "./src/server.ts" : "./src/chainlink-cli.ts",
    ...(isServer ? ["--outdir", "./dist"] : ["--outfile", "./dist/chainlink-loop.js"]),
    "--target",
    "bun",
    ...externals.flatMap((name) => ["--external", name]),
    ...defineArgs,
  ]
  execFileSync(process.execPath, args, { cwd: root, stdio: "inherit" })
}

const requested = (process.argv[2] ?? "all") as Target
if (requested !== "all" && requested !== "server" && requested !== "cli") {
  throw new Error(`unknown build target "${requested}" (expected all, server, or cli)`)
}
if (requested === "all" || requested === "server") build("server")
if (requested === "all" || requested === "cli") build("cli")

mkdirSync(fileURLToPath(new URL("../dist", import.meta.url)), { recursive: true })
writeFileSync(
  new URL("../dist/build-info.json", import.meta.url),
  `${JSON.stringify(buildInfo, null, 2)}\n`,
)

console.log(
  `[build] ${buildInfo.version} ${buildInfo.gitDescribe ?? buildInfo.gitSha ?? "unknown"}${
    buildInfo.gitDirty ? " (dirty)" : ""
  }`,
)
